"""
MEDHA — Production Question Loader
Loads verified questions from JSONL file into the SQLite database.
"""

import sys
import os
import json
from pathlib import Path

# Add backend directory to sys.path to allow importing modules
backend_dir = Path(__file__).parent.parent
sys.path.append(str(backend_dir))

from database import SessionLocal, init_db
from models import Question

def run():
    print("Initializing Database...")
    init_db()
    
    db = SessionLocal()
    
    # Check if already seeded
    existing = db.query(Question).count()
    if existing > 0:
        print(f"Database already contains {existing} questions.")
        print("To reload, delete medha.db first. Skipping seed.")
        return

    data_file = backend_dir / "data" / "questions_clean.jsonl"
    if not data_file.exists():
        print(f"ERROR: {data_file} not found.")
        return

    mapping_file = backend_dir / "data" / "question_pdf_mapping.json"
    pdf_mappings = {}
    if mapping_file.exists():
        print("Found PDF coordinate mappings, loading...")
        with open(mapping_file, 'r', encoding='utf-8') as f:
            pdf_mappings = json.load(f)

    print(f"Loading questions from {data_file.name}...")
    
    loaded_count = 0
    with open(data_file, 'r', encoding='utf-8') as f:
        for line in f:
            q_data = json.loads(line.strip())
            q_id = q_data.get("id")
            
            # Extract options
            opts = q_data.get("options", {})
            opt_a = opts.get("A", {}).get("bn", "")
            opt_b = opts.get("B", {}).get("bn", "")
            opt_c = opts.get("C", {}).get("bn", "")
            opt_d = opts.get("D", {}).get("bn", "")
            
            # Get PDF mapping if available
            mapping = pdf_mappings.get(q_id)
            pdf_file = mapping["file"] if mapping else None
            pdf_page = mapping["page"] if mapping else None
            pdf_bbox = mapping["bbox"] if mapping else None
            
            db_q = Question(
                year=str(q_data.get("year", "Unknown")),
                subject=q_data.get("subject", "Biology"),
                chapter_code=q_data.get("chapter_code", "GEN"),
                chapter_name=q_data.get("chapter_name_bn", ""),
                topic=q_data.get("topic", ""),
                difficulty=q_data.get("difficulty", "medium"),
                question_bn=q_data.get("question_bn", ""),
                option_a_bn=opt_a,
                option_b_bn=opt_b,
                option_c_bn=opt_c,
                option_d_bn=opt_d,
                correct=q_data.get("correct", "A"),
                explanation_bn=q_data.get("explanation_bn", ""),
                memory_trick="", # Will be generated by Qwen later
                trap_note=q_data.get("confusable_note", ""),
                frequency=q_data.get("frequency", 1),
                verified=q_data.get("verified", True),
                pdf_file=pdf_file,
                pdf_page=pdf_page,
                pdf_bbox=pdf_bbox
            )
            db.add(db_q)
            loaded_count += 1
    
    db.commit()
    print(f"[SUCCESS] Seeding complete! Inserted {loaded_count} questions.")
    
    # Verify
    count = db.query(Question).count()
    print(f"Total questions in DB: {count}")
    
    db.close()

if __name__ == "__main__":
    run()
