import { useRef, useCallback, useMemo } from "react";
import { Download, Share2, MessageCircle, Facebook } from "lucide-react";
import { t, computeAnxiety } from "../utils/lang";

export default function ShareCard({ attempt, lang }) {
  const canvasRef = useRef(null);
  const r = useMemo(() => attempt.readiness || {}, [attempt.readiness]);
  const anx = useMemo(() => computeAnxiety(attempt), [attempt]);

  const generateCard = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    const W = 800, H = 480;
    canvas.width = W; canvas.height = H;

    // Background (Dark theme for high contrast social shares)
    const bg = ctx.createLinearGradient(0, 0, W, H);
    bg.addColorStop(0, "#1C1815"); bg.addColorStop(1, "#2D2420");
    ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H);

    // Accent orange radial glow
    const glow = ctx.createRadialGradient(W - 60, 60, 0, W - 60, 60, 320);
    glow.addColorStop(0, "rgba(211,74,32,0.35)"); glow.addColorStop(1, "transparent");
    ctx.fillStyle = glow; ctx.fillRect(0, 0, W, H);

    // Rounded Border
    ctx.strokeStyle = "rgba(255,255,255,0.08)"; ctx.lineWidth = 1;
    ctx.roundRect(8, 8, W - 16, H - 16, 20); ctx.stroke();

    // Wordmark
    ctx.fillStyle = "#fff"; ctx.font = "bold 26px 'Plus Jakarta Sans', sans-serif";
    ctx.fillText("MEDHA", 40, 56);
    ctx.fillStyle = "rgba(255,255,255,0.4)"; ctx.font = "12px 'Plus Jakarta Sans', sans-serif";
    ctx.fillText("BEHAVIORAL DNA", 40, 78);

    // Divider
    ctx.strokeStyle = "rgba(255,255,255,0.08)"; ctx.beginPath();
    ctx.moveTo(40, 94); ctx.lineTo(W - 40, 94); ctx.stroke();

    // Score readouts
    ctx.fillStyle = "rgba(255,255,255,0.6)"; ctx.font = "13px 'Plus Jakarta Sans', sans-serif";
    ctx.fillText(lang === "bn" ? "ভর্তি প্রস্তুতি স্তর" : "MBBS Readiness Index", 40, 140);
    ctx.fillStyle = "#D34A20"; ctx.font = "bold 82px 'Hind Siliguri', serif";
    ctx.fillText(`${r.score ?? 70}%`, 40, 220);

    // Stats grid
    const stats = [
      { label: lang === "bn" ? "সঠিক" : "Correct", value: `${r.correct}/${r.total}`, color: "#395F54" },
      { label: lang === "bn" ? "মাস্টার" : "Mastered", value: `${r.master}`, color: "#395F54" },
      { label: lang === "bn" ? "ধীর" : "Slow", value: `${r.slow}`, color: "#C37A28" },
      { label: lang === "bn" ? "গোলমাল" : "Confused", value: `${r.confused}`, color: "#5057A6" },
      { label: lang === "bn" ? "বিপদ" : "Danger", value: `${r.danger}`, color: "#C03A2A" },
      { label: lang === "bn" ? "গড় সময়" : "Avg Time", value: `${r.avgTime}s`, color: "#D34A20" },
    ];

    let sx = 340, sy = 150;
    stats.forEach((s, i) => {
      const x = sx + (i % 3) * 140;
      const y = sy + Math.floor(i / 3) * 90;

      // Stats title
      ctx.fillStyle = "rgba(255,255,255,0.4)"; ctx.font = "11px 'Plus Jakarta Sans', sans-serif";
      ctx.fillText(s.label.toUpperCase(), x, y);

      // Stats value
      ctx.fillStyle = "#fff"; ctx.font = "bold 26px 'Hind Siliguri', serif";
      ctx.fillText(s.value, x, y + 28);
    });

    // Pill
    ctx.fillStyle = "rgba(255, 255, 255, 0.05)"; ctx.beginPath();
    ctx.roundRect(40, 310, 240, 36, 18); ctx.fill();
    ctx.fillStyle = "rgba(255,255,255,0.7)"; ctx.font = "600 12px 'Plus Jakarta Sans', sans-serif";
    ctx.fillText(lang === "bn" ? "উদ্বেগ লেভেল: মাঝারি" : `Anxiety Level: ${anx.level.toUpperCase()}`, 60, 332);

    // Footer Line
    ctx.strokeStyle = "rgba(255,255,255,0.06)"; ctx.beginPath();
    ctx.moveTo(40, H - 70); ctx.lineTo(W - 40, H - 70); ctx.stroke();

    // Footer Branding
    ctx.fillStyle = "rgba(255,255,255,0.3)"; ctx.font = "12px 'Plus Jakarta Sans', sans-serif";
    ctx.fillText("Generated by MEDHA — Biology Behavioral Exam Prep", 40, H - 36);
    ctx.fillText("MBBS Admission 2025", W - 180, H - 36);

    // Trigger Download
    const link = document.createElement("a");
    link.download = "medha-behavioral-dna.png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  }, [r, anx, lang]);

  return (
    <div className="view fade-in" data-testid="share-view" style={{ background: "var(--paper)" }}>
      <div className="container-md screen-inner" style={{ paddingTop: 32 }}>
        
        {/* Title */}
        <div className="reveal show" style={{ marginBottom: 28 }}>
          <span className="pill" style={{ display: "inline-flex", alignItems: "center", gap: 6 }}>
            <Share2 size={13} />
            {lang === "bn" ? "ফলাফল শেয়ার" : "Share Results"}
          </span>
          <h2 className="display" style={{ fontSize: "clamp(32px, 5vw, 48px)", marginTop: 14, marginBottom: 8 }}>
            {lang === "bn" ? "অর্জিত সাফল্য শেয়ার করুন" : "Share Your Achievements"}
          </h2>
          <p style={{ color: "var(--muted)", fontSize: "14.5px", lineHeight: 1.7 }}>
            {lang === "bn"
              ? "আপনার কগনিটিভ মাস্টারির সাফল্য উদযাপন করুন। সহপাঠী ও শিক্ষকদের সাথে কার্ডটি শেয়ার করুন।"
              : "Celebrate your cognitive mastery. Share your personalized Medha DNA card with classmates, mentors, or on social media."}
          </p>
        </div>

        {/* 2-Column layout */}
        <div className="share-grid">
          
          {/* Left: preview and share tools */}
          <div>
            <div className="share-stat-chips">
              <div className="share-chip">
                <div className="share-chip-lbl">{lang === "bn" ? "সঠিক" : "Correct"}</div>
                <div className="share-chip-val" style={{ color: "var(--master)" }}>{r.correct} / {r.total}</div>
              </div>
              <div className="share-chip">
                <div className="share-chip-lbl">{lang === "bn" ? "রেডিনেস" : "Readiness"}</div>
                <div className="share-chip-val" style={{ color: "var(--brand)" }}>{r.score}%</div>
              </div>
              <div className="share-chip">
                <div className="share-chip-lbl">{lang === "bn" ? "উদ্বেগ" : "Anxiety"}</div>
                <div className="share-chip-val" style={{ color: anx.score > 50 ? "var(--danger)" : "var(--master)" }}>{anx.score}</div>
              </div>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              <button className="btn btn-primary" style={{ padding: "12px 20px", display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 12 }} onClick={generateCard}>
                <Download size={16} />
                {t("shareDownload", lang)}
              </button>

              <div className="platform-btns">
                <a className="platform-btn whatsapp" href={`https://api.whatsapp.com/send?text=${encodeURIComponent(`I completed the MEDHA Behavioral Exam! My MBBS Readiness Index is ${r.score}%. Check out your learning DNA!`)}`} target="_blank" rel="noopener noreferrer">
                  <MessageCircle size={16} />
                  WhatsApp
                </a>
                <a className="platform-btn facebook" href="https://facebook.com" target="_blank" rel="noopener noreferrer">
                  <Facebook size={16} />
                  Facebook
                </a>
              </div>
            </div>
          </div>

          {/* Right: Premium Dark Card Preview */}
          <div style={{ display: "flex", justifyContent: "center" }}>
            <div className="share-card-preview" style={{ position: "relative", width: "100%", maxWidth: 380 }}>
              <div className="share-card-accent"></div>
              <div className="sc-brand" style={{ letterSpacing: ".15em" }}>MEDHA — BEHAVIORAL DNA</div>
              <div className="sc-score" style={{ color: "white", fontSize: 64, fontWeight: 700, fontFamily: "'Hind Siliguri', serif" }}>
                {r.score}%
              </div>
              <div className="sc-label" style={{ opacity: 0.6, fontSize: 13, marginBottom: 40 }}>
                {lang === "bn" ? "ভর্তি প্রস্তুতি স্তর" : "MBBS Readiness Index"}
              </div>
              <div className="sc-bottom" style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
                <div>
                  <div style={{ fontSize: 20, fontWeight: 700, fontFamily: "'Hind Siliguri', serif", color: "white" }}>
                    {r.correct} / {r.total}
                  </div>
                  <div style={{ fontSize: 11, opacity: 0.5, textTransform: "uppercase" }}>
                    {lang === "bn" ? "সঠিক উত্তর" : "Correct"}
                  </div>
                </div>
                <div className="sc-tag" style={{ opacity: 0.5, fontSize: 11 }}>MBBS 2025</div>
              </div>
            </div>
          </div>

        </div>

        <canvas ref={canvasRef} style={{ display: "none" }} />

        <div className="page-footer" style={{ paddingBottom: 40, marginTop: 40 }}>
          {lang === "bn" ? "মেধা — কগনিটিভ DNA কার্ড" : "MEDHA — Cognitive DNA Sharing"}
        </div>
      </div>
    </div>
  );
}
