import { useRef, useCallback } from "react";
import { Download, Share2 } from "lucide-react";
import { t, computeAnxiety } from "../utils/lang";

export default function ShareCard({ attempt, lang }) {
  const canvasRef = useRef(null);
  const r = attempt.readiness;
  const anx = computeAnxiety(attempt);

  const generateCard = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    const W = 800, H = 480;
    canvas.width = W; canvas.height = H;

    // Background
    const bg = ctx.createLinearGradient(0, 0, W, H);
    bg.addColorStop(0, "#0e0e11"); bg.addColorStop(1, "#16161a");
    ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H);

    // Accent glow
    const glow = ctx.createRadialGradient(W * 0.5, 0, 0, W * 0.5, 0, 400);
    glow.addColorStop(0, "rgba(124,111,255,0.18)"); glow.addColorStop(1, "transparent");
    ctx.fillStyle = glow; ctx.fillRect(0, 0, W, H);

    // Border
    ctx.strokeStyle = "rgba(255,255,255,0.08)"; ctx.lineWidth = 1;
    ctx.roundRect(8, 8, W - 16, H - 16, 16); ctx.stroke();

    // Logo
    ctx.fillStyle = "#fff"; ctx.font = "bold 28px 'Segoe UI', sans-serif";
    ctx.fillText("MEDHA", 36, 52);
    ctx.fillStyle = "#7c6fff"; ctx.font = "600 28px 'Segoe UI', sans-serif";
    ctx.fillText(".", 36 + ctx.measureText("MEDHA").width, 52);

    // Tagline
    ctx.fillStyle = "#a1a1aa"; ctx.font = "13px 'Segoe UI', sans-serif";
    ctx.fillText("Behavioral Intelligence Exam Report", 36, 74);

    // Divider
    ctx.strokeStyle = "rgba(255,255,255,0.08)"; ctx.beginPath();
    ctx.moveTo(36, 90); ctx.lineTo(W - 36, 90); ctx.stroke();

    // Score ring (drawn manually)
    const cx = 140, cy = 200, rad = 56;
    ctx.beginPath(); ctx.arc(cx, cy, rad, 0, Math.PI * 2);
    ctx.strokeStyle = "rgba(255,255,255,0.06)"; ctx.lineWidth = 8; ctx.stroke();

    const pct = r.correct / r.total;
    const arcColor = pct >= 0.6 ? "#22c97a" : pct >= 0.4 ? "#f5a623" : "#ff4f6a";
    ctx.beginPath();
    ctx.arc(cx, cy, rad, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * pct);
    ctx.strokeStyle = arcColor; ctx.lineWidth = 8; ctx.lineCap = "round"; ctx.stroke();

    ctx.fillStyle = "#fff"; ctx.font = "bold 36px 'Segoe UI', sans-serif";
    ctx.textAlign = "center"; ctx.fillText(`${r.correct}`, cx, cy + 6);
    ctx.fillStyle = "#a1a1aa"; ctx.font = "14px 'Segoe UI', sans-serif";
    ctx.fillText(`/ ${r.total}`, cx, cy + 26);
    ctx.textAlign = "left";

    // Stats grid
    const stats = [
      { label: "Readiness", value: `${r.score}%`, color: "#7c6fff" },
      { label: "Mastered", value: `${r.master}`, color: "#22c97a" },
      { label: "Confused", value: `${r.confused}`, color: "#f5a623" },
      { label: "Danger", value: `${r.danger}`, color: "#ff4f6a" },
      { label: "Avg Time", value: `${r.avgTime}s`, color: "#7c6fff" },
      { label: "Anxiety", value: `${anx.score}`, color: anx.score > 50 ? "#ff4f6a" : "#22c97a" },
    ];

    let sx = 260, sy = 120;
    stats.forEach((s, i) => {
      const x = sx + (i % 3) * 170;
      const y = sy + Math.floor(i / 3) * 80;
      ctx.fillStyle = s.color; ctx.font = "bold 28px 'Segoe UI', monospace";
      ctx.fillText(s.value, x, y);
      ctx.fillStyle = "#6b6b76"; ctx.font = "12px 'Segoe UI', sans-serif";
      ctx.fillText(s.label, x, y + 20);
    });

    // Group pills row
    const groups = [
      { label: "Mastered", count: r.master, color: "#22c97a" },
      { label: "Slow", count: r.slow, color: "#f5a623" },
      { label: "Confused", count: r.confused, color: "#7c6fff" },
      { label: "Danger", count: r.danger, color: "#ff4f6a" },
    ];
    let px = 36;
    const py2 = 330;
    ctx.font = "600 13px 'Segoe UI', sans-serif";
    groups.forEach((g) => {
      const text = `${g.label}: ${g.count}`;
      const tw = ctx.measureText(text).width + 24;
      ctx.fillStyle = g.color + "1a"; ctx.beginPath();
      ctx.roundRect(px, py2, tw, 30, 12); ctx.fill();
      ctx.strokeStyle = g.color + "40"; ctx.lineWidth = 1;
      ctx.beginPath(); ctx.roundRect(px, py2, tw, 30, 12); ctx.stroke();
      ctx.fillStyle = g.color;
      ctx.fillText(text, px + 12, py2 + 20);
      px += tw + 10;
    });

    // Footer
    ctx.fillStyle = "rgba(255,255,255,0.06)";
    ctx.fillRect(36, H - 60, W - 72, 1);
    ctx.fillStyle = "#6b6b76"; ctx.font = "12px 'Segoe UI', sans-serif";
    ctx.fillText("Generated by MEDHA — Behavioral Intelligence Exam Platform", 36, H - 30);
    ctx.fillText(new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }), W - 140, H - 30);

    // Download
    const link = document.createElement("a");
    link.download = "medha-report-card.png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  }, [r, anx]);

  return (
    <div className="view" data-testid="share-view">
      <div className="wrap">
        <div className="section-head">
          <span className="pill"><Share2 size={13} /> {t("shareTitle", lang)}</span>
          <h2 style={{ marginTop: 16 }}>{t("shareTitle", lang)}</h2>
          <p>{t("shareSub", lang)}</p>
        </div>

        <div className="share-preview card">
          <div className="share-preview-inner">
            <div className="share-logo">MEDHA<span>.</span></div>
            <div className="share-tag">Behavioral Intelligence Exam Report</div>
            <div className="share-stats-row">
              <div className="share-stat">
                <span className="ss-val" style={{ color: "var(--accent)" }}>{r.score}%</span>
                <span className="ss-lbl">Readiness</span>
              </div>
              <div className="share-stat">
                <span className="ss-val" style={{ color: "var(--green)" }}>{r.correct}/{r.total}</span>
                <span className="ss-lbl">Correct</span>
              </div>
              <div className="share-stat">
                <span className="ss-val" style={{ color: "var(--green)" }}>{r.master}</span>
                <span className="ss-lbl">Mastered</span>
              </div>
              <div className="share-stat">
                <span className="ss-val" style={{ color: "var(--red)" }}>{r.danger}</span>
                <span className="ss-lbl">Danger</span>
              </div>
              <div className="share-stat">
                <span className="ss-val" style={{ color: anx.score > 50 ? "var(--red)" : "var(--green)" }}>{anx.score}</span>
                <span className="ss-lbl">Anxiety</span>
              </div>
            </div>
          </div>
        </div>

        <canvas ref={canvasRef} style={{ display: "none" }} />

        <div style={{ marginTop: 20, display: "flex", justifyContent: "center" }}>
          <button className="btn btn-primary" data-testid="download-card" onClick={generateCard}>
            <Download size={16} style={{ marginRight: 8, verticalAlign: "middle" }} />
            {t("shareDownload", lang)}
          </button>
        </div>
      </div>
    </div>
  );
}
